In [4]:
import pandas as pd 
import numpy as np 

In [1]:
from sklearn import datasets
iris = datasets.load_iris()

In [14]:
iris.data 
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [30]:
hero_info = pd.read_csv('王者荣耀.csv')
hero_info = np.array(hero_info)
hero_target

array([3, 2, 1, 2, 2, 2, 5, 5, 6, 6, 2, 4, 1, 6, 2, 3, 2, 1, 2, 3, 2, 1,
       1, 1, 4, 5, 5, 1, 3, 2, 1, 1, 2, 2, 3, 1, 2, 3, 4, 2, 4, 1, 2, 2,
       4, 4, 1, 4, 6, 5, 1, 6, 5, 5, 6, 5, 1, 1, 6, 6, 1, 2, 5, 6, 6, 2,
       6, 1, 5, 4, 3, 1, 2, 6, 5, 2, 4, 2, 1, 2, 4, 1, 4, 6, 5, 2, 1, 2,
       2, 3, 1, 6, 4, 1, 1, 2, 6, 5, 4, 1, 3, 1, 4, 1, 5, 1, 2, 4])

In [23]:
hero_data = hero_info[:,2:6].astype(int)
hero_target = hero_info[:,6].astype(int)

In [27]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf = clf.fit(hero_data, hero_target)

In [29]:
y_pred=clf.predict(hero_data)
y_pred

array([3, 2, 1, 1, 2, 2, 5, 5, 6, 3, 2, 5, 1, 2, 1, 3, 1, 1, 2, 3, 2, 1,
       1, 1, 4, 4, 5, 1, 3, 2, 1, 1, 2, 2, 3, 2, 2, 3, 4, 2, 5, 1, 2, 2,
       5, 1, 3, 1, 3, 5, 1, 3, 5, 5, 2, 5, 1, 1, 2, 2, 6, 2, 5, 2, 6, 2,
       6, 1, 4, 4, 1, 3, 2, 6, 5, 2, 4, 1, 1, 2, 4, 1, 2, 3, 5, 2, 1, 2,
       6, 1, 1, 2, 5, 1, 4, 2, 6, 5, 2, 1, 3, 1, 4, 1, 5, 4, 5, 5])